### ISSUE TITLE
create html

### ISSUE THREAD

**Issue by ChaitanyaM07** [MIniProject-SL/MiniProject-Repo#13]

**Comment by Om3101** [comment]
Done

**Comment by Om3101** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <h1>TIC-TAC-TOE</h1>
    <div class="winner hide">
    </div>
    <div class="body">
    <div class="container">
         <div class="boxes">
            <button class="eachbox"></button>
            <button class="eachbox"></button>
            <button class="eachbox"></button>
            <button class="eachbox"></button>
            <button class="eachbox"></button>
            <button class="eachbox"></button>
            <button class="eachbox"></button>
            <button class="eachbox"></button>
            <button class="eachbox"></button>
        </div>
    </div>
    </div>
</body>
<script src="script.js"></script>
</html>
